#!/bin/bash

set -euC
# set -o pipefail

# exec 5>> /tmp/xmosh/shell-script-debug.out
# BASH_XTRACEFD="5"
# PS4='$LINENO: '
# set -x

app="$(readlink "$0")"

source "$(dirname "$app")/.env/bin/activate"

python "${app}.py" "$@"
